language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache:
  timeout: 360
  cargo: true

script:
  - cargo test --all
  - cargo test --all --no-default-features
  
matrix:
  allow_failures:
    - rust: nightly
